# Site settings
title: All out ATL
email: april23organizingcommittee@riseup.net
#url: https://marthavandella.github.io/
url: https://alloutatl.com/
description: "Mobilize to shut down the KKK march in Stone Mountain, GA.  April 23rd, 2016: Everyone out against white supremacy!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: El pueblo

# Social networks usernames (many more available: github,bitbucket,stack-overflow,google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/alloutatlanta
# - title: facebook
#    url: https://twitter.com/SBootstrap

# Build settings
markdown: kramdown
permalink: pretty
